string firstName;
//"Bob" = firstName;
//int firstName;
firstName = "Bob";
//string firstName;
firstName = "Bob";
Console.WriteLine(firstName);
//string firstName;
firstName = "Bob";
Console.WriteLine(firstName);
firstName = "Liem";
Console.WriteLine(firstName);
firstName = "Isabella";
Console.WriteLine(firstName);
firstName = "Yasmin";
Console.WriteLine(firstName);
//string firstName;
Console.WriteLine(firstName);
//string firstName = "Bob";
Console.WriteLine(firstName);